AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/script/**/*'
    - Rakefile
    - Gemfile
  UseCache: true
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'api/endpoints/**/*'
Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'api/**/*'
    - 'lib/**/*'
