language: ruby
os: linux
sudo: false

before_install:
  - gem install bundler

rvm:
  - ruby-head
  - 2.7.0
  - 2.6.5
  - 2.5.7

jobs:
  fast_finish: true

  allow_failures:
    - rvm:
      - ruby-head
